blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(('records.urls', 'records'), namespace='records')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path
from .views import *

urlpatterns = [

 path('dashboard/', dashboard, name='dashboard'),
 path('technology/<int:technology_id>/', technologies, name='technology'),
 path('<str:name>/<int:blog_id>/', blog_details, name='blog_details'),
 path('logout/', logout, name='logout'),
 path('add-blog/', BlogCreation.as_view(), name='add-blog'),
 path('accounts/signup', signup, name='signup'),
 path('blog-comments/<int:blog_id>/<str:comment>', save_comment, name='blog-comment'),
# path('update_blog', update_blog),
 path('increase_like/<int:comm_id>', increase_like, name='increase_like'),
 #path('consume_blog', consume_blog),



]

records/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Category:
    Name = (
        ('Python', 'Python'),
        ('JavaScript', 'JavaScript'),
        ('Linux', 'Linux'),
        ('Django', 'Django'),
        ('Java', 'Java'),
        ('ML', 'ML')
    )


# Create your models here.
class Team(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    photo = models.ImageField(null=False, blank=False, upload_to='media/')
    member_about = models.CharField(max_length=40, null=True, blank=True)
    class Meta:
        default_permissions = ('view')
                       

    def __str__(self):
        return str(self.name)


class Details(models.Model):
    about = models.CharField(max_length=200, null=False, blank=False)
    contact = models.CharField(max_length=20, blank=False)
    email = models.EmailField(max_length=20, blank=False, null=False)

    def __str__(self):
        return self.contact


class BlogCategory(models.Model):
    name = models.CharField(max_length=20, choices=Category.Name, blank=False, null=False)
    description = models.CharField(max_length=200, blank=False, null=False)
    blog_photo = models.ImageField(blank=False, null=False, upload_to='media/')

    def __str__(self):
        return self.name


class BlogDetails(models.Model):
    technology = models.ForeignKey(BlogCategory, on_delete=models.CASCADE, null=False, blank=False, verbose_name="Technology")
    short_details = models.CharField(max_length=40, null=False, blank=False, verbose_name="Short Details")
    description = RichTextField(null=False, blank=False, verbose_name="Description")
    blog_details_photo = models.ImageField(null=True, blank=True, upload_to='Attachments/', verbose_name="Code Snippet")
    written_by = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, verbose_name="Written By")
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return str(self.technology)+ "-->" + str(self.short_details)


class BlogComments(models.Model):
    blog_id = models.ForeignKey(BlogDetails, on_delete=models.CASCADE)
    comments = models.TextField(null=True, blank=True)
    like = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, verbose_name="User")
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    liked_user = models.TextField(default="string")

    def __str__(self):
        return str(self.comments)

records/forms.py
from .models import *
from django.forms import ModelForm


class BlogDetailsForm(ModelForm):
    class Meta:
        model = BlogDetails
        exclude = ('comments',)
        fields = ('technology', 'short_details', 'description', 'blog_details_photo', )

records/views.py
from django.shortcuts import render, redirect
from .models import *
from django.views.generic import View
from .forms import BlogDetailsForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('records:dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


def dashboard(request):
    details = Details.objects.filter(id=1).values('about', 'email', 'contact')
#file1= BlogDetails.objects.filter(id=23)
#   file1=file1.blog_details_photo.name
#   print(file1)
    s = str(request.user)
    if s == 'AnonymousUser':

        user = False

    else:
        user = User.objects.get(username=request.user.username)

    context = {
        'details': details,
        'user': user
    }
    return render(request, 'index.html', context)


def technologies(request, technology_id):
    s = str(request.user)

    if s == 'AnonymousUser':

        user = False

    else:
        user = User.objects.get(username=request.user.username)
    technology_details = BlogDetails.objects.filter(technology=technology_id, approved=True).values('id',
                                                                                                    'technology__name',
                                                                                                    'short_details',
                                                                                                    'written_by__username',
                                                                                                    'created_at').order_by(
        '-id')

    details = Details.objects.filter(id=1).values('about', 'email', 'contact')
    return render(request, 'blogs/technology.html',
                  {'technology_details': technology_details, 'details': details, 'user': user})


def blog_details(request, name, blog_id):
    details = Details.objects.filter(id=1).values('about', 'email', 'contact')
    s = str(request.user)

    if s == 'AnonymousUser':

        user = False

    else:
        user = User.objects.get(username=request.user.username)

    blog_details = BlogDetails.objects.filter(technology__name=name, pk=blog_id).values('id','technology__name',
                                                                                        'short_details', 'description',
                                                                                        'blog_details_photo',
                                                                                        'written_by')

    comment = BlogComments.objects.filter(blog_id=blog_id).order_by('-id').values('id', 'comments', 'user__username',
                                                                                  'created_at', 'like')[:15]

    return render(request, 'blogs/blog_details.html',
                  {'blog_details': blog_details, 'details': details, 'comment': comment, 'user': user})


@method_decorator(login_required, name='dispatch')
class BlogCreation(View):
    def get(self, request):
        form = BlogDetailsForm()
        return render(request, 'forms/addForm.html', {"form": form
                                                      })

    def post(self, request):
        post = request.POST.copy()
        user = User.objects.get(username=request.user.username)
        request.POST = post

        form = BlogDetailsForm(request.POST, request.FILES)

        if form.is_valid():
            new = form.save(commit=False)
            new.written_by= user

            new.save()

            return HttpResponseRedirect(reverse('records:dashboard'))
        else:

            return render(request, 'forms/addForm.html',
                          {"form": form, })


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('records:dashboard'))


@login_required
def save_comment(request, blog_id, comment):

        user = User.objects.get(username=request.user.username)
        pki = BlogComments.objects.create(blog_id=BlogDetails.objects.get(pk=blog_id), comments=comment, user=user)
        result = list(BlogComments.objects.filter(pk=pki.id).order_by('comments').values('id', 'comments', 'like',
                                                                                         'user__username',
                                                                                         'created_at'))

        result[0]['created_at'] = '0 min ago'

        return JsonResponse(result, safe=False)


@login_required
def increase_like(request, comm_id):
    like = BlogComments.objects.get(id=comm_id)

    if request.user.username in like.liked_user:
        like_no = BlogComments.objects.get(id=comm_id)
        print(like_no.like)
        like_count = like_no.like - 1
        user = like_no.liked_user.replace(request.user.username,"")
        like_no.like = like_count
        like_no.liked_user = user
        like_no.save()
        return JsonResponse(like_count, safe=False)

    else:
        like_no = BlogComments.objects.get(id=comm_id)
        print(like_no.like)
        users = like_no.liked_user
        like_count = like_no.like + 1
        like_no.like = like_count
        like_no.liked_user = users+","+request.user.username
        like_no.save()
        return JsonResponse(like_count, safe=False)

records/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Code Aatma</title>

  <!-- Bootstrap core CSS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->





  <link href="{% static 'css/agency.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

   <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style="background:black; height:25px;">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">Code Aatma</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'records:dashboard' %}">Dashboard</a>
          </li>
             <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
           {% if  not user %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color:yellow" href="/accounts/login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color:yellow" href="/accounts/signup">Sign Up</a>
          </li>
          {% else %}
           <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'records:add-blog' %}" style="color:yellow">Add BLog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'records:logout' %}" style="color:yellow">Logout</a>
          </li>

          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

   <br>


   {% block content %}
    {% endblock %}
  <footer class="footer">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-4">
          <span class="copyright">Copyright &copy; Your Website 2019</span>
        </div>
        <div class="col-md-4">
          <ul class="list-inline social-buttons">
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-4">
          <ul class="list-inline quicklinks">
            <li class="list-inline-item">
              <a href="#">Privacy Policy</a>
            </li>
            <li class="list-inline-item">
              <a href="#">Terms of Use</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>




  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Contact form JavaScript -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/agency.min.js"></script>
  <script src="{% static 'js/test.js' %}"></script>
  <script src="{% static 'js/jquery.js' %}"></script>

</body>



</html>

records/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!--<meta name="description" content=""> -->

   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="author" content="">

  <title>Blog</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/agency.min.css' %}" rel="stylesheet">

</head>


<body id="page-top">


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background:black; height:25px;">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Reading</a>
      {% if user %}

            <a class="nav-link js-scroll-trigger" style="color:white; text-transform: uppercase;">Hello {{user.username}}</a>
      {% endif %}

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color:yellow" href="{% url 'records:dashboard' %}">Dashboard</a>
          </li>

          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color:yellow" href="#portfolio">Technologies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger"  style="color:yellow" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color:yellow" href="#team">Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color:yellow" href="#contact">Contact</a>
          </li>
          {% if  not user %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color:yellow" href="/accounts/login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color:yellow" href="/accounts/signup">Sign Up</a>
          </li>
          {% else %}
           <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'records:add-blog' %}" style="color:yellow">Add BLog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'records:logout' %}" style="color:yellow">Logout</a>
          </li>

          {% endif %}


        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
<!-- Header -->
  <header class="masthead">
    <div class="container">
      <div class="intro-text">


        <div class="intro-lead-in">Welcome To Our Blog!</div>
        <div class="intro-heading text-uppercase">It's Nice To Meet You</div>
      </div>
    </div>
  </header>



  <!-- Portfolio Grid -->
  <section class="bg-light page-section" id="portfolio">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">Technologies</h2>
          <h3 class="section-subheading text-muted">Be a Technical guy.</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-sm-6 portfolio-item">
          <a class="portfolio-link"  href="/technology/1">
            <div class="portfolio-hover">
              <div>
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid"  src="{% static 'img/portfolio/python.jpg' %}"alt="">
          </a>
          <div class="portfolio-caption">
            <h4>Python</h4>

          </div>
        </div>
        <div class="col-md-4 col-sm-6 portfolio-item">
          <a class="portfolio-link" href="/technology/3">
            <div class="portfolio-hover">
              <div>
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="{% static 'img/portfolio/javascript.jpg' %}" style="height:260px" alt="">
          </a>
          <div class="portfolio-caption">
            <h4>Java Script</h4>
          </div>
        </div>
        <div class="col-md-4 col-sm-6 portfolio-item">
          <a class="portfolio-link" href="/technology/4">
            <div class="portfolio-hover">
              <div>
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="{% static 'img/portfolio/linux.jpg' %}" alt=""
            style="height:260px; width:350px">
          </a>
          <div class="portfolio-caption">
            <h4>Linux</h4>

          </div>
        </div>
        <div class="col-md-4 col-sm-6 portfolio-item">
          <a class="portfolio-link" href="/technology/5">
            <div class="portfolio-hover">
              <div>
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="{% static 'img/portfolio/Django.png' %}" style="height:230px;width: fit-content;" alt="">
          </a>
          <div class="portfolio-caption">
            <h4>Django</h4>
          </div>
        </div>
        <div class="col-md-4 col-sm-6 portfolio-item">
          <a class="portfolio-link"
 href="/technology/6">
            <div class="portfolio-hover">
              <div>
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="{% static 'img/portfolio/java.jpg' %}" alt="">
          </a>
          <div class="portfolio-caption">
            <h4>Java</h4>

          </div>
        </div>
        <div class="col-md-4 col-sm-6 portfolio-item">
          <a class="portfolio-link"  href="/technology/2">
            <div class="portfolio-hover">
              <div>
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="{% static 'img/portfolio/ml.jpg' %}" alt="">
          </a>
          <div class="portfolio-caption">
            <h4>Machine Learning</h4>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- About -->
  <section class="page-section" id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">About</h2>
          <h3 class="section-subheading text-muted">We are Happy</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <ul class="timeline">
            <li>
              <div class="timeline-image">
                <img class="rounded-circle img-fluid" src="{% static 'img/about/1.jpg' %}" alt="">
              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">

                  <h4 class="subheading">Our Humble Beginnings</h4>
                </div>
                <div class="timeline-body">
                  {% for details in details %}
                  <p class="text-muted">{{details.about}}</p>
                  {% endfor %}
                </div>
              </div>
            </li>

            <li class="timeline-inverted">
              <div class="timeline-image">
                <h4>Be Part
                  <br>Of Our
                  <br>Blog
                <br>Call Us!</h4>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <!-- Team -->
  <section class="bg-light page-section" id="team">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">Our Amazing Team</h2>
          <h3 class="section-subheading text-muted"></h3>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="team-member">
            <div class="col-md-6" style="float: centre;margin-left: 232px;">

            <img class="mx-auto rounded-circle" src="{% static 'img/team/me.jpg' %}" alt="">
            <h4>Vaibhav Mishra</h4>
            <p class="text-muted">Lead</p>
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>
            </ul>
            </div>
            
          </div>
        </div>
       
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <p class="large text-muted"></p>
      </div>
    </div>
  </section>


  <!-- Contact -->
  <section class="page-section" id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">Contact Us</h2>
          <h3 class="section-subheading text-muted"></h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          {% for details in details %}
          <div style="text-align:center;color:white; font-size:xx-large">
            <i class="fa fa-phone" aria-hidden="true"></i>
            {{details.contact}}<br>
          <i class="fa fa-envelope-square" aria-hidden="true"></i>
            {{details.email}}</div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer class="footer">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-4">
          <span class="copyright">Copyright &copy; Your Website 2019</span>
        </div>
        <div class="col-md-4">
          <ul class="list-inline social-buttons">
            <li class="list-inline-item">
              <a href="https://www.instagram.com/code_aatma/?igshid=og9f597hwg0x">
                <i class="fab fa-instagram" aria-hidden="true"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-4">
          <ul class="list-inline quicklinks">
            <li class="list-inline-item">
              <a href="#">Privacy Policy</a>
            </li>
            <li class="list-inline-item">
              <a href="#">Terms of Use</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>




  <!-- Bootstrap core JavaScript -->
  <script src="{{ STATIC_URL }} /static/vendor/jquery/jquery.min.js"></script>
  <script src="{{ STATIC_URL }} /static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="{{ STATIC_URL }} /static/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Contact form JavaScript -->
  <script src="{{ STATIC_URL }} /static/js/jqBootstrapValidation.js"></script>
  <script src="{{ STATIC_URL }} /static/js/contact_me.js"></script>

  <!-- Custom scripts for this template -->
  <script src="{{ STATIC_URL }} /static/js/agency.min.js"></script>


</body>

</html>